# Filename: irrigation_unlimited_smart_irrigation.yaml
#
# Verion: 1.0.4
#
# Description: Example automation for HAsmartirrigation integration
# (smart_irrigation)[https://github.com/jeroenterheerdt/HAsmartirrigation]
#
# This automation tracks a Smart Irrigation sensor and transfers the
# the calculation to a Irrigation Unlimited sequence. When the sequence
# completes the Smart Irrigation bucket is reset.
#
# Change the relevant Smart Irrigation and Irrigation Unlimited entities.
# DO NOT simply copy this file as it will NOT WORK, it must be configured
# to suit your setup as indicated below.
#
# This file is a package and should be located in the config/packages
# folder. If you do not have a packages folder then create it and add
# the following to configuration.yaml
#
# homeassistant:
#  packages: !include_dir_named packages
#
# More information on packages can be found at https://www.home-assistant.io/docs/configuration/packages
#
automation:
  - alias: Smart Irrigation adjustment
    id: "IU1653097957047"
    description: Adjust watering times based on smart irrigation calculations
    mode: single
    triggers:
      - trigger: state
        # Change the Smart Irrigation entity_id as required
        entity_id: sensor.smart_irrigation_[zone_name]
        to: null
    actions:
      - action: irrigation_unlimited.adjust_time
        data:
          actual: "{{ timedelta(seconds=trigger.to_state.state | int(0)) }}"
          # Change the Irrigation Unlimited sequence entity_id as required
          entity_id: binary_sensor.irrigation_unlimited_c1_s1

  - alias: Smart Irrigation reset bucket
    id: "IU1653098247170"
    description: Resets the Smart Irrigation bucket after watering
    mode: single
    triggers:
      - trigger: event
        event_type: irrigation_unlimited_finish
    condition:
      - "{{ trigger.event.data.schedule.index }}" # Not a manual run
      # Match the following to the Irrigation Unlimited entity_id as above
      - "{{ trigger.event.data.entity_id == 'binary_sensor.irrigation_unlimited_c1_s1' }}"
    actions:
      - action: smart_irrigation.reset_bucket
        # Match the following to the Smart Irrigation entity_id as above
        entity_id: sensor.smart_irrigation_[zone_name]
        data: {}
