"""Constants for irrigation_unlimited."""

# Base component constants
NAME = "Irrigation Unlimited"
DOMAIN = "irrigation_unlimited"
DOMAIN_DATA = f"{DOMAIN}_data"
COORDINATOR = "coordinator"
COMPONENT = "component"
VERSION = "2025.10.0"
ATTRIBUTION = "Data provided by http://jsonplaceholder.typicode.com/"
ISSUE_URL = "https://github.com/rgc99/irrigation_unlimited/issues"

# Icons
ICON = "mdi:zodiac-aquarius"
ICON_BLOCKED = "mdi:alert-octagon-outline"
ICON_CONTROLLER_DELAY = "mdi:timer-sand"
ICON_CONTROLLER_OFF = "mdi:water-off"
ICON_CONTROLLER_ON = "mdi:water"
ICON_CONTROLLER_PAUSED = "mdi:pause-circle-outline"
ICON_DISABLED = "mdi:circle-off-outline"
ICON_SEQUENCE_DELAY = "mdi:timer-sand"
ICON_SEQUENCE_OFF = "mdi:stop-circle-outline"
ICON_SEQUENCE_ON = "mdi:play-circle-outline"
ICON_SEQUENCE_PAUSED = "mdi:pause-circle-outline"
ICON_SEQUENCE_ZONE_OFF = "mdi:stop-circle-outline"
ICON_SEQUENCE_ZONE_ON = "mdi:play-circle-outline"
ICON_SUSPENDED = "mdi:timer-outline"
ICON_ZONE_OFF = "mdi:valve-closed"
ICON_ZONE_ON = "mdi:valve-open"

# Platforms
BINARY_SENSOR = "binary_sensor"
PLATFORMS = [BINARY_SENSOR]

# Configuration and options
CONF_ACTUAL = "actual"
CONF_ALLOW_MANUAL = "allow_manual"
CONF_ALL_ZONES_CONFIG = "all_zones_config"
CONF_ANCHOR = "anchor"
CONF_AUTOPLAY = "autoplay"
CONF_CHAINS = "chains"
CONF_CHECK_BACK = "check_back"
CONF_CLOCK = "clock"
CONF_CONFIG = "config"
CONF_CONTROLLER = "controller"
CONF_CONTROLLERS = "controllers"
CONF_CONTROLLER_ID = "controller_id"
CONF_CRON = "cron"
CONF_DAY = "day"
CONF_DECREASE = "decrease"
CONF_DURATION = "duration"
CONF_ENABLED = "enabled"
CONF_END = "end"
CONF_ENTITY_BASE = "entity_base"
CONF_ENTITY_STATES = "entity_states"
CONF_EVEN = "even"
CONF_EVERY_N_DAYS = "every_n_days"
CONF_EXPECTED = "expected"
CONF_EXTENDED = "extended"
CONF_EXTENDED_CONFIG = "extended_config"
CONF_FINISH = "finish"
CONF_FIXED = "fixed"
CONF_FLOW_RATE_PRECISION = "flow_rate_precision"
CONF_FLOW_RATE_SCALE = "flow_rate_scale"
CONF_FOUND = "found"
CONF_FROM = "from"
CONF_FUTURE_SPAN = "future_span"
CONF_GLOBAL_SEQUENCE_IDS = "global_sequence_ids"
CONF_GLOBAL_ZONE_IDS = "global_zone_ids"
CONF_GRANULARITY = "granularity"
CONF_HISTORY = "history"
CONF_HISTORY_REFRESH = "history_refresh"
CONF_HISTORY_SPAN = "history_span"
CONF_INCREASE = "increase"
CONF_INDEX = "index"
CONF_LOGGING = "logging"
CONF_MAXIMUM = "maximum"
CONF_MAX_LOG_ENTRIES = "max_log_entries"
CONF_MINIMUM = "minimum"
CONF_MODE = "mode"
CONF_MONTH = "month"
CONF_ODD = "odd"
CONF_OUTPUT_EVENTS = "output_events"
CONF_PERCENTAGE = "percentage"
CONF_POSTAMBLE = "postamble"
CONF_PREAMBLE = "preamble"
CONF_QUEUE = "queue"
CONF_QUEUE_MANUAL = "queue_manual"
CONF_READ_DELAY = "read_delay"
CONF_REFRESH_INTERVAL = "refresh_interval"
CONF_RENAME_ENTITIES = "rename_entities"
CONF_RESET = "reset"
CONF_RESTORE_FROM_ENTITY = "restore_from_entity"
CONF_RESULTS = "results"
CONF_RESYNC = "resync"
CONF_RETRIES = "retries"
CONF_RUN = "run"
CONF_SCHEDULE = "schedule"
CONF_SCHEDULES = "schedules"
CONF_SCHEDULE_ID = "schedule_id"
CONF_SEER = "seer"
CONF_SEQUENCE = "sequence"
CONF_SEQUENCES = "sequences"
CONF_SEQUENCE_ID = "sequence_id"
CONF_SEQUENCE_ZONE = "sequence_zone"
CONF_SEQUENCE_ZONES = "sequence_zones"
CONF_SHOW = "show"
CONF_SHOW_CONFIG = "show_config"
CONF_SHOW_LOG = "show_log"
CONF_SHOW_SEQUENCE_STATUS = "show_sequence_status"
CONF_SPAN = "span"
CONF_SPEED = "speed"
CONF_START = "start"
CONF_START_N_DAYS = "start_n_days"
CONF_STATES = "states"
CONF_STATE_OFF = "state_off"
CONF_STATE_ON = "state_on"
CONF_SUN = "sun"
CONF_SYNC_SWITCHES = "sync_switches"
CONF_TESTING = "testing"
CONF_THRESHOLD = "threshold"
CONF_TIME = "time"
CONF_TIMELINE = "timeline"
CONF_TIMES = "times"
CONF_TOGGLE = "toggle"
CONF_USER = "user"
CONF_VERSION = "version"
CONF_VOLUME = "volume"
CONF_VOLUME_PRECISION = "volume_precision"
CONF_VOLUME_SCALE = "volume_scale"
CONF_ZONE = "zone"
CONF_ZONES = "zones"
CONF_ZONE_ID = "zone_id"
CONF_ZONE_IDS = "zone_ids"

# Defaults
DEFAULT_GRANULARITY = 60
DEFAULT_MAX_LOG_ENTRIES = 50
DEFAULT_NAME = DOMAIN
DEFAULT_REFRESH_INTERVAL = 30
DEFAULT_TEST_SPEED = 1.0

# Services
SERVICE_CANCEL = "cancel"
SERVICE_DISABLE = "disable"
SERVICE_ENABLE = "enable"
SERVICE_GET_INFO = "get_info"
SERVICE_GET_STATUS = "get_status"
SERVICE_LOAD_SCHEDULE = "load_schedule"
SERVICE_MANUAL_RUN = "manual_run"
SERVICE_PAUSE = "pause"
SERVICE_RESUME = "resume"
SERVICE_SKIP = "skip"
SERVICE_SUSPEND = "suspend"
SERVICE_TIME_ADJUST = "adjust_time"
SERVICE_TOGGLE = "toggle"

# Events
EVENT_FINISH = "finish"
EVENT_INCOMPLETE = "incomplete"
EVENT_START = "start"
EVENT_SWITCH_ERROR = "switch_error"
EVENT_SYNC_ERROR = "sync_error"
EVENT_VALVE_OFF = "valve_off"
EVENT_VALVE_ON = "valve_on"

# Status
STATUS_BLOCKED = "blocked"
STATUS_DELAY = "delay"
STATUS_DISABLED = "disabled"
STATUS_INITIALISING = "initialising"
STATUS_PAUSED = "paused"
STATUS_SUSPENDED = "suspended"

# Timeline labels
TIMELINE_ADJUSTMENT = "adjustment"
TIMELINE_END = "end"
TIMELINE_SCHEDULE = "schedule"
TIMELINE_SCHEDULE_NAME = "schedule_name"
TIMELINE_START = "start"
TIMELINE_STATUS = "status"

# Attributes
ATTR_ADJUSTED_DURATION = "adjusted_duration"
ATTR_ADJUSTMENT = "adjustment"
ATTR_BASE_DURATION = "base_duration"
ATTR_CONFIGURATION = "configuration"
ATTR_CONTROLLER = "controller"
ATTR_CONTROLLERS = "controllers"
ATTR_CONTROLLER_COUNT = "controller_count"
ATTR_CONTROLLER_ID = "controller_id"
ATTR_CURRENT_ADJUSTMENT = "current_adjustment"
ATTR_CURRENT_DURATION = "current_duration"
ATTR_CURRENT_NAME = "current_name"
ATTR_CURRENT_SCHEDULE = "current_schedule"
ATTR_CURRENT_START = "current_start"
ATTR_CURRENT_ZONE = "current_zone"
ATTR_DEFAULT_DELAY = "default_delay"
ATTR_DEFAULT_DURATION = "default_duration"
ATTR_DURATION = "duration"
ATTR_DURATION_FACTOR = "duration_factor"
ATTR_ENABLED = "enabled"
ATTR_FINAL_DURATION = "final_duration"
ATTR_FLOW_RATE = "flow_rate"
ATTR_ID = "id"
ATTR_INDEX = "index"
ATTR_IU_ID = "iu_id"
ATTR_NAME = "name"
ATTR_NEXT_ADJUSTMENT = "next_adjustment"
ATTR_NEXT_DURATION = "next_duration"
ATTR_NEXT_NAME = "next_name"
ATTR_NEXT_SCHEDULE = "next_schedule"
ATTR_NEXT_START = "next_start"
ATTR_NEXT_TICK = "next_tick"
ATTR_NEXT_ZONE = "next_zone"
ATTR_PERCENT_COMPLETE = "percent_complete"
ATTR_REPEAT = "repeat"
ATTR_RUN = "run"
ATTR_SCHEDULE = "schedule"
ATTR_SCHEDULE_COUNT = "schedule_count"
ATTR_SCHEDULE_ID = "schedule_id"
ATTR_SEQUENCE = "sequence"
ATTR_SEQUENCES = "sequences"
ATTR_SEQUENCE_COUNT = "sequence_count"
ATTR_SEQUENCE_ID = "sequence_id"
ATTR_SEQUENCE_STATUS = "sequence_status"
ATTR_START = "start"
ATTR_STATUS = "status"
ATTR_SUSPENDED = "suspended"
ATTR_SWITCH_ENTITIES = "switch_entity_id"
ATTR_TICK_LOG = "tick_log"
ATTR_TIMELINE = "timeline"
ATTR_TIME_REMAINING = "time_remaining"
ATTR_TOTAL_DELAY = "total_delay"
ATTR_TOTAL_DURATION = "total_duration"
ATTR_TOTAL_TODAY = "today_total"
ATTR_TYPE = "type"
ATTR_VERSION = "version"
ATTR_VOLUME = "volume"
ATTR_ZONE = "zone"
ATTR_ZONES = "zones"
ATTR_ZONE_COUNT = "zone_count"
ATTR_ZONE_ID = "zone_id"
ATTR_ZONE_IDS = "zone_ids"

# Resources
RES_MANUAL = "Manual"
RES_NONE = "none"
RES_NOT_RUNNING = "not running"
RES_TIMELINE_HISTORY = "history"
RES_TIMELINE_NEXT = "next"
RES_TIMELINE_RUNNING = "running"
RES_TIMELINE_SCHEDULED = "scheduled"

MONTHS = [
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
]

STARTUP_MESSAGE = f"""
-------------------------------------------------------------------
{NAME}
Version: {VERSION}
If you have any issues with this you need to open an issue here:
{ISSUE_URL}
-------------------------------------------------------------------
"""
